/* 
 *  This file is part of the Chronus Quantum (ChronusQ) software package
 *  
 *  Copyright (C) 2014-2022 Li Research Group (University of Washington)
 *  
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *  
 *  Contact the Developers:
 *    E-Mail: xsli@uw.edu
 *  
 */
#pragma once

#include <chronusq_sys.hpp>
#include <cubegen.hpp>

namespace ChronusQ {

    /**
     * @brief Writes header of cube file
     * 
     * This creates the header at the beginning of the cube file,
     *  diplaying the dimensions of the surface in the cube format
    */
    void CubeGen::writeSummary() {
      std::map<CUBE_TYPE, std::string> cubeTypeOut = {
          {CUBE_TYPE::_CHARGE_DENSITY, "CHARGE DENSITY"},
          {CUBE_TYPE::_SPIN_DENSITY, "SPIN DENSITY"},
          {CUBE_TYPE::_ELECTROSTATIC_POTENTIAL, "ELECTROSTATIC POTENTIAL"}
      };
      std::vector<double> centerPoint = calcCenter();

      *cubeFile_ << cubeFilename_ << "\n";
      *cubeFile_ << std::fixed;

      *cubeFile_ << cubeTypeOut[cubeType_];
      *cubeFile_ << " : GENERATED BY CHRONUSQ\n";


      size_t nAtoms = ref_->molecule().nAtoms;
      Molecule &mol = ref_->molecule();

      double x_edge = 0.0 - voxelUnits_[0]*(double)voxelGrid_[0]/2.0;
      double y_edge = 0.0 - voxelUnits_[1]*(double)voxelGrid_[1]/2.0;
      double z_edge = 0.0 - voxelUnits_[2]*(double)voxelGrid_[2]/2.0;

      *cubeFile_ << std::setprecision(6);

      *cubeFile_ << std::setw(6) << std::right << nAtoms;
      *cubeFile_ << std::setw(15) << x_edge;
      *cubeFile_ << std::setw(15) << y_edge;
      *cubeFile_ << std::setw(15) << z_edge;
      *cubeFile_ << "\n";


      *cubeFile_ << std::setw(6) << std::right << voxelGrid_[0];
      *cubeFile_ << std::setw(15) << voxelUnits_[0];
      *cubeFile_ << std::setw(15) << 0.;
      *cubeFile_ << std::setw(15) << 0.;
      *cubeFile_ << "\n";

      *cubeFile_ << std::setw(6) << std::right << voxelGrid_[1];
      *cubeFile_ << std::setw(15) << 0.;
      *cubeFile_ << std::setw(15) << voxelUnits_[1];
      *cubeFile_ << std::setw(15) << 0.;
      *cubeFile_ << "\n";

      *cubeFile_ << std::setw(6) << std::right << voxelGrid_[2];
      *cubeFile_ << std::setw(15) << 0.;
      *cubeFile_ << std::setw(15) << 0.;
      *cubeFile_ << std::setw(15) << voxelUnits_[2];
      *cubeFile_ << "\n";

      for( auto &atom : ref_->molecule().atoms ) {

        *cubeFile_ << std::setw(6) << atom.atomicNumber;
        *cubeFile_ << std::setw(15) << 0.;

        *cubeFile_ << std::setw(15) << atom.coord[0];
        *cubeFile_ << std::setw(15) << atom.coord[1];
        *cubeFile_ << std::setw(15) << atom.coord[2];

        *cubeFile_ << "\n";

      }

    }

    /**
     * @brief run-type function for cubegen 
     * 
    */
    template <typename LocMatsT>
    void CubeGen::evalCube(CUBE_TYPE cubeCall, std::shared_ptr<cqmatrix::PauliSpinorMatrices<LocMatsT>> oPDM) {

      std::cout << std::endl;
      std::cout << "----------------------------------------------------" << std::endl;
      std::cout << "Generating Cube file for: " << cubeFilename_ << std::endl;
      std::cout << "Using " << voxelGrid_[0] << "," << voxelGrid_[1] << "," << voxelGrid_[2] << " Points" << std::endl;
      std::cout << "With steps: " << voxelUnits_[0] << "," << voxelUnits_[1] << "," << voxelUnits_[2] << std::endl;
      std::cout << "Cube padding: " << cubePadding_ << std::endl;
      std::cout << "----------------------------------------------------" << std::endl;
      std::cout << std::endl;

      
      ProgramTimer::tick("Cube Eval");

      // assign to object field
      cubeType_ = cubeCall;

      // write the cubefile header 
      writeSummary();

      if (cubeType_ == CUBE_TYPE::_CHARGE_DENSITY) {
        evalCDCube(oPDM);
      }
      else
      {
         CErr("CubeGen for non-Charge Density Cubes NYI!");
       }
      ProgramTimer::tock("Cube Eval");

      std::cout << std::endl;
      std::cout << "----------------------------------------------------" << std::endl;
      std::cout << "Finished generating Cube file for: " << cubeFilename_ << std::endl;
      std::cout << "----------------------------------------------------" << std::endl;
      std::cout << std::endl;

      
    }


}
