name: CQ CI - CMake Configure, Build, Test, Cache
on:
  push:
    branches: dev
  pull_request:
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
   cmake-build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 200
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "GCC",
            os: [self-hosted, nix],
            enable_mpi: OFF,
            c_compiler: gcc,
            cxx_compiler: g++,
            fortran_compiler: gfortran,
            para_build_jobs: 7,
            para_test_jobs: 7
          }
          - {
            name: "GCC-MPI",
            os: [self-hosted, nix],
            enable_mpi: ON,
            c_compiler: mpicc,
            cxx_compiler: mpicxx,
            fortran_compiler: mpifort,
            para_build_jobs: 7,
            para_test_jobs: 4
          }           
    steps:
      - name: Checkout Current CQ Branch
        uses: actions/checkout@v3
     
      # Set Environment
      - name: Set up environment
        run: |
          env
          mkdir -p build

      # Restore ccache
      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ runner.name }}-${{ matrix.config.enable_mpi }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ runner.name }}-${{ matrix.config.enable_mpi }}-

      - name: Install and configure ccache
        shell: bash
        run: |
          nix develop /home/runners/nix-env --command bash -c '
            if ! command -v ccache &> /dev/null; then
              echo "ccache not found in nix flake shell."
              exit 1
            fi
            ccache --zero-stats
            ccache --show-config
          '

      # Configure
      - name: Configure
        shell: bash
        working-directory: build
        run: |
          nix develop /home/runners/nix-env --command bash -c '
            export OMPI_ALLOW_RUN_AS_ROOT=1
            export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
            cmake .. \
              -DCQ_ENABLE_MPI=${{ matrix.config.enable_mpi }} \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_C_COMPILER=${{ matrix.config.c_compiler }} \
              -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx_compiler }} \
              -DCMAKE_Fortran_COMPILER=${{ matrix.config.fortran_compiler }} \
              -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
              -DCMAKE_C_COMPILER_LAUNCHER=ccache \
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
              -DCMAKE_COLOR_DIAGNOSTICS=On \
              -S .. -B .
          '

      # Build
      - name: Build
        shell: bash
        working-directory: build
        run: |
          echo "Building with ${{ matrix.config.para_build_jobs }} threads"
          nix develop /home/runners/nix-env --command bash -c '
            cmake --build . --config Release --parallel ${{ matrix.config.para_build_jobs }}
          '

      # Show ccache stats
      - name: Show ccache stats
        run: |
          nix develop /home/runners/nix-env --command ccache --show-stats

      # Test
      - name: Test
        shell: bash
        working-directory: build
        run: |
          echo "Testing with ${{ matrix.config.para_test_jobs }} threads"
          nix develop /home/runners/nix-env --command bash -c '
            export OMPI_ALLOW_RUN_AS_ROOT=1
            export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
            ctest -E "GPLHR" --output-on-failure --parallel ${{ matrix.config.para_test_jobs }}
            ctest -R "GPLHR" --output-on-failure
          '