name: CQ CI - CMake Configure, Build, Test, Cache

on:
  push:
    branches: dev
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
   cmake-build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 200
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "GCC",
            os: [self-hosted, gcc],
            enable_mpi: OFF,
            para_build_jobs: 7,
            para_test_jobs: 7
          }
          - {
            name: "GCC-MPI",
            os: [self-hosted, gcc, mpi],
            enable_mpi: ON,
            para_build_jobs: 7,
            para_test_jobs: 4
          }           
    steps:
      - name: Checkout Current CQ Branch
        uses: actions/checkout@v3
     
      # Set Environment
      - name: Set up environment
        run: |
          env
          mkdir -p build

      # Restore ccache
      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ runner.name }}-${{ matrix.config.enable_mpi }}-${{ hashFiles('**/CMakeLists.txt') }}  # Unique key based on CMakeLists.txt and mpi enabled changes
          restore-keys: |
            ${{ runner.os }}-ccache-${{ runner.name }}-${{ matrix.config.enable_mpi }}-

      - name: Install and configure ccache
        shell: bash
        run: |
          if ! command -v ccache &> /dev/null; then
            echo "ccache not found, please install it on runner."
            exit 1
          fi
          ccache --zero-stats
          ccache --show-config

      # Configure
      - name: Configure
        shell: bash
        working-directory: build
        run: |
          source /usr/share/Modules/init/bash
          source /etc/profile.d/modules.sh
          export MODULEPATH=/home/modulefiles/compilers:/home/modulefiles/compiler_dep/gcc/10.2.0:/home/modulefiles:$MODULEPATH
          module load gcc hdf5 libint
          export PATH=/usr/lib64/openmpi/bin:$PATH
          export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:/home/software/gcc/10/2/0/install/lib64:$LD_LIBRARY_PATH

          cmake .. \
            -DCQ_ENABLE_MPI=${{ matrix.config.enable_mpi }} \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_COLOR_DIAGNOSTICS=On \
            -DBLAS_LIBRARIES=/usr/lib64/libopenblas.so \
            -DLAPACK_LIBRARIES=/usr/lib64/libopenblas.so \
            -G Ninja \
            -S .. -B .

      # Build
      - name: Build
        shell: bash
        working-directory: build
        run: |
          echo "Building with ${{ matrix.config.para_build_jobs }} threads"
          cmake --build . --config Release --parallel ${{ matrix.config.para_build_jobs }}

      # Show ccache stats
      - name: Show ccache stats
        run: ccache --show-stats

      # Test
      - name: Test
        shell: bash
        working-directory: build
        run: |
          echo "Testing with ${{ matrix.config.para_test_jobs }} threads"
          source /usr/share/Modules/init/bash
          source /etc/profile.d/modules.sh
          export MODULEPATH=/home/modulefiles/compilers:/home/modulefiles/compiler_dep/gcc/10.2.0:/home/modulefiles:$MODULEPATH
          module load gcc hdf5 libint
          export PATH=/usr/lib64/openmpi/bin:$PATH
          export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:/home/software/gcc/10/2/0/install/lib64:$LD_LIBRARY_PATH

          ctest -E "GPLHR" --output-on-failure --parallel ${{ matrix.config.para_test_jobs }}
          ctest -R "GPLHR" --output-on-failure

