name: CQ CI - CMake Configure, Build, Test, Cache

on:
  push:
    branches: dev
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
   cmake-build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 200
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "GCC",
            os: [self-hosted, gcc],
            enable_mpi: OFF,
            additional_cmake_args: -DCQ_ENABLE_MPI=OFF,
          }
          - {
            name: "GCC-MPI",
            os: [self-hosted, gcc, mpi],
            enable_mpi: On,
            additional_cmake_args: -DCQ_ENABLE_MPI=ON,
          }           
    steps:
      - name: Checkout Current CQ Branch
        uses: actions/checkout@v3
     
      - name: Set up environment
        run: |
          env
          mkdir -p build

      - name: Cache build based on CMakeLists.txt and mpi enabled
        id: cache-build
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-build-${{ runner.name }}-${{ matrix.config.enable_mpi }}-${{ hashFiles('**/CMakeLists.txt') }}  # Unique key based on CMakeLists.txt and mpi enabled changes
          restore-keys: |
            ${{ runner.os }}-build-${{ runner.name }}-${{ matrix.config.enable_mpi }}-
      
      - name: Check if build is cached
        run: |
          if [[ "${{ steps.cache-build.outputs.cache-hit }}" == "true" ]]; then
            echo "Build cache restored, skipping rebuild."
            echo "skip_build=true" >> $GITHUB_ENV
          else
            echo "No cached build found, proceeding with rebuild."
            echo "skip_build=false" >> $GITHUB_ENV
          fi 
      - name: Configure
        if: env.skip_build == 'false'
        shell: bash
        working-directory: build
        run: |
          #Load environment
          source /usr/share/Modules/init/bash
          source /etc/profile.d/modules.sh
          export MODULEPATH=/home/modulefiles/compilers:/home/modulefiles/compiler_dep/gcc/10.2.0:/home/modulefiles:$MODULEPATH

          module load gcc
          module load hdf5
          module load libint
          export PATH=/usr/lib64/openmpi/bin:$PATH
          export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:/home/software/gcc/10/2/0/install/lib64:$LD_LIBRARY_PATH
          #build
          cmake .. \
            -DCQ_ENABLE_MPI=${{ matrix.config.enable_mpi }} \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_COLOR_DIAGNOSTICS=On \
            -DBLAS_LIBRARIES=/usr/lib64/libopenblas.so \
            -DLAPACK_LIBRARIES=/usr/lib64/libopenblas.so \
            -G Ninja \
            -S .. -B .
           
      - name: Build
        if: env.skip_build == 'false'
        shell: bash
        working-directory: build
        run: |
              JOBS=7
              echo "Building with $JOBS threads"
              cmake --build . --config Release --parallel $JOBS
      
      - name: Test
        shell: bash
        working-directory: build
        run: |
              if [ "${{ matrix.config.enable_mpi }}" = "On" ]; then
                JOBS=4 # Lower number of threads if using MPI
              else
                JOBS=7 
              fi
              echo "Testing with $JOBS threads"
              # Load environment
              source /usr/share/Modules/init/bash
              source /etc/profile.d/modules.sh
              export MODULEPATH=/home/modulefiles/compilers:/home/modulefiles/compiler_dep/gcc/10.2.0:/home/modulefiles:$MODULEPATH

              module load gcc
              module load hdf5
              module load libint
              export PATH=/usr/lib64/openmpi/bin:$PATH
              export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:/home/software/gcc/10/2/0/install/lib64:$LD_LIBRARY_PATH
              #run test
              ctest -E "GPLHR" --output-on-failure --parallel $JOBS # Run all test GPLHR in parrallel
              ctest -R "GPLHR" --output-on-failure # Run GPLHR in serial

