name: CQ CI - CMake Configure, Build, Test

on:
  push:
    branches: dev
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cmake-build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 1440
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "GCC",
            os: [self-hosted, cache],
            enable_mpi: OFF,
            additional_cmake_args: -DCQ_ENABLE_MPI=OFF,
            parallel_build_tasks: 1
          }
          - {
            name: "GCC-MPI",
            os: [self-hosted, gcc, mpi],
            enable_mpi: ON,
            additional_cmake_args: -DCQ_ENABLE_MPI=ON,
            parallel_build_tasks: 1
          }
    steps:
      - name: Checkout Current CQ Branch
        uses: actions/checkout@v3

      - name: Cache CMake Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/CMake  # Replace with your actual cache directory if needed
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}  # Cache key based on CMakeLists.txt file hash
          restore-keys: |
            ${{ runner.os }}-cmake-
      
      - name: Set up environment
        run: |
          env
          mkdir build

      - name: Configure
        shell: bash
        working-directory: build
        run: |
          source scl_source enable gcc-toolset-13
          cmake \
            -DCQ_ENABLE_MPI=${{ matrix.config.enable_mpi }} \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_COLOR_DIAGNOSTICS=On \
            -G Ninja \
            -S .. -B .

      - name: Build
        shell: bash
        working-directory: build
        run: |
          cmake --build . \
                --config Release \
                --parallel ${{ matrix.config.parallel_build_tasks }}

      - name: Test
        shell: bash
        working-directory: build
        run: |
          ctest . \
                --output-on-failure \
                --parallel ${{ matrix.config.parallel_build_tasks }}
